### ISSUE TITLE
Can u please make this as an app apk

### ISSUE THREAD

**Issue by Aruraka** [whouishere/kissasian.go#1]
Hello there ,can u please make this as an app apk for those who don't have  computer ..and can u make it such a way that the downloaded shows from kissasian will stay in the app itself instead of in theinternal memory of phone also

**Comment by whouishere** [comment]
This was an educational project I made and abandoned years ago, and it wasn't even close to being finished. It was never meant to be something where you could watch or download dramas, the project just fetched info about a very specific drama from kissasian. It never was a kissasian client.

And no, I couldn't make it a mobile app, since it wasn't event meant to be in the first place, nor would it ever make sense to, since it wasn't designed to watch dramas in it.

If you want an actual app to watch dramas in, I recommend [Aniyomi](https://aniyomi.org/), I use it to watch dramas on my phone.

And **please**, stop making issues on random people's projects, especially if requesting for random impossible features. Yes, you can issue a feature request on GitHub, issues have that purpose too. But first check if the project has anything to do with your request (this project, for example, **does not**), if the feature is even possible or reasonable to ask in the first place and, most importantly, if the issue you're creating already exists. If you still are not sure about any of those three points, don't worry, you can always research about the topics the project involves and how they work. Google is your friend, and you might learn something in the way too.

And if there isn't anything that meets your needs, I absolutely recommend you to learn programming and look into web scraping. There are tons of great and easy mobile frameworks you could learn to make an app in (Flutter, Jetpack Compose, NativeScript), and an app that scrapes a streaming website is an awesome project to properly learn programming. My advice is: don't give up on programming. It just gets more fun and challenging, but absolutely rewarding.
